### PR TITLE
Migrate to null safety

### PR DESCRIPTION
**Pull request by LiquidPL**
This PR migrates the package to be null safe, while also moving from `pedantic` lints to the currently recommended Dart lints. I've also commented out some tests that were failing presumably because 16-bit depth chunks are not implemented.

### CODE REVIEW

**Comment by lukepighetti** [comment]
@patchandthat, this PR author has done a great service here, I hope that you will provide them the review they deserve for their efforts

**Comment by patchandthat** [comment]
Thankyou for the prompt, I didn't get a notification when the PR was opened.  I'll take a look this evening.

**Comment by lukepighetti** [comment]
I have also had this problem on my own repos, apologies for the ping.

**Comment by patchandthat** [comment]
@LiquidPL Thank you for the PR. I'll merge this now and then fix up the commented out tests on my side before publishing. 👍

**Pull request merged**
